[package]
name = "lobby-client-lib"
version = "0.1.0"
authors = ["LÃ©onard Besson <leonard.besson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
lobby-lib = { path = "lobby-lib" }
